# Phase-1 and Phase-2 System Module
# Global pool progression mechanism that automatically upgrades users through different phases and slots
# WHEN A PERSON JOINS THE GLOBAL POOL WITH $33, THEY ARE PLACED IN SLOT 1 OF PHASE 1
# ONCE 4 PEOPLE ARE PLACED GLOBALLY UNDER THEM, THEIR SLOT IS AUTOMATICALLY UP-GRADED, AND THEY MOVE TO PHASE 2, OCCUPYING SLOT 1 THERE
# WHEN THEIR SLOT 1 IN PHASE 2 IS COMPLETED WITH 8 PEOPLE GLOBALLY UNDER THEM, THEY RE-ENTER PHASE 1 AND ARE PLACED IN SLOT 2
# THIS PROCESS CONTINUES, FOLLOWING THE DIAGRAM BELOW, UNTIL REACHING SLOT 16
